# Generated by Django 3.0.6 on 2020-07-13 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_remove_partner_resume'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='resume',
            field=models.FileField(null=True, upload_to='media'),
        ),
    ]
