# Generated by Django 3.0.6 on 2020-06-20 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_manage_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='manager',
            new_name='managed',
        ),
    ]
