# Generated by Django 3.0.6 on 2020-07-14 10:13

import accounts.database
import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_partner_resume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientprofile',
            name='Aadhar_card',
            field=models.FileField(max_length=200, upload_to=accounts.database.client_aadhar, validators=[accounts.models.validate_file_extension]),
        ),
        migrations.AlterField(
            model_name='clientprofile',
            name='Certificate_of_Inc',
            field=models.FileField(max_length=200, upload_to=accounts.database.client_coinc, validators=[accounts.models.validate_file_extension]),
        ),
        migrations.AlterField(
            model_name='clientprofile',
            name='Company_Pan_card',
            field=models.FileField(max_length=200, upload_to=accounts.database.client_cpan, validators=[accounts.models.validate_file_extension]),
        ),
        migrations.AlterField(
            model_name='clientprofile',
            name='Official_photo',
            field=models.ImageField(max_length=200, upload_to=accounts.database.client_photo),
        ),
        migrations.AlterField(
            model_name='clientprofile',
            name='Pan_card',
            field=models.FileField(max_length=200, upload_to=accounts.database.client_pan, validators=[accounts.models.validate_file_extension]),
        ),
        migrations.AlterField(
            model_name='clientprofile',
            name='Payment_slip',
            field=models.FileField(max_length=200, upload_to=accounts.database.client_ps, validators=[accounts.models.validate_file_extension]),
        ),
        migrations.AlterField(
            model_name='clientprofile',
            name='TAN_Document',
            field=models.FileField(max_length=200, upload_to=accounts.database.client_tan, validators=[accounts.models.validate_file_extension]),
        ),
        migrations.AlterField(
            model_name='clientprofile',
            name='logo',
            field=models.ImageField(max_length=200, upload_to=accounts.database.client_logo),
        ),
        migrations.AlterField(
            model_name='order',
            name='documents',
            field=models.FileField(max_length=200, upload_to=accounts.database.order, validators=[accounts.models.validate_file_extension]),
        ),
        migrations.AlterField(
            model_name='partner',
            name='resume',
            field=models.FileField(null=True, upload_to=accounts.database.partner_resume),
        ),
        migrations.AlterField(
            model_name='partnerprofile',
            name='Aadhar_card',
            field=models.FileField(max_length=200, upload_to=accounts.database.partner_aadhar, validators=[accounts.models.validate_file_extension]),
        ),
        migrations.AlterField(
            model_name='partnerprofile',
            name='Educational_certificate',
            field=models.FileField(max_length=200, upload_to=accounts.database.partner_ec, validators=[accounts.models.validate_file_extension]),
        ),
        migrations.AlterField(
            model_name='partnerprofile',
            name='Official_photo',
            field=models.ImageField(upload_to=accounts.database.partner_photo),
        ),
        migrations.AlterField(
            model_name='partnerprofile',
            name='Pan_card',
            field=models.FileField(max_length=200, upload_to=accounts.database.partner_pan, validators=[accounts.models.validate_file_extension]),
        ),
        migrations.AlterField(
            model_name='partnerprofile',
            name='Payment_slip',
            field=models.FileField(max_length=200, upload_to=accounts.database.partner_ps, validators=[accounts.models.validate_file_extension]),
        ),
        migrations.AlterField(
            model_name='partnerprofile',
            name='Work_experience',
            field=models.FileField(max_length=200, upload_to=accounts.database.partner_worexp, validators=[accounts.models.validate_file_extension]),
        ),
        migrations.AlterField(
            model_name='product',
            name='documents',
            field=models.FileField(max_length=200, upload_to=accounts.database.product, validators=[accounts.models.validate_file_extension]),
        ),
    ]
