# Generated by Django 3.0.7 on 2020-07-03 12:49

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_auto_20200702_1720'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='documents',
            field=models.FileField(max_length=200, upload_to='media', validators=[accounts.models.validate_file_extension]),
        ),
        migrations.AlterField(
            model_name='product',
            name='documents',
            field=models.FileField(max_length=200, upload_to='media', validators=[accounts.models.validate_file_extension]),
        ),
    ]
