# Generated by Django 3.0.7 on 2020-07-05 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20200703_1819'),
    ]

    operations = [
        migrations.AddField(
            model_name='partner',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
