# Generated by Django 3.0.7 on 2020-07-06 14:13

import accounts.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_partner_is_approved'),
    ]

    operations = [
        migrations.CreateModel(
            name='Partnerprofile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Official_photo', models.ImageField(upload_to='media')),
                ('Aadhar_card', models.FileField(max_length=200, upload_to='media', validators=[accounts.models.validate_file_extension])),
                ('Pan_card', models.FileField(max_length=200, upload_to='media', validators=[accounts.models.validate_file_extension])),
                ('Work_experience', models.FileField(max_length=200, upload_to='media', validators=[accounts.models.validate_file_extension])),
                ('Payment_slip', models.FileField(max_length=200, upload_to='media', validators=[accounts.models.validate_file_extension])),
                ('Educational_certificate', models.FileField(max_length=200, upload_to='media', validators=[accounts.models.validate_file_extension])),
                ('partner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.Partner')),
            ],
        ),
        migrations.CreateModel(
            name='Clientprofile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(upload_to='media')),
                ('Official_photo', models.ImageField(upload_to='media')),
                ('Aadhar_card', models.FileField(max_length=200, upload_to='media', validators=[accounts.models.validate_file_extension])),
                ('Pan_card', models.FileField(max_length=200, upload_to='media', validators=[accounts.models.validate_file_extension])),
                ('Certificate_of_Inc', models.FileField(max_length=200, upload_to='media', validators=[accounts.models.validate_file_extension])),
                ('Company_Pan_card', models.FileField(max_length=200, upload_to='media', validators=[accounts.models.validate_file_extension])),
                ('Payment_slip', models.FileField(max_length=200, upload_to='media', validators=[accounts.models.validate_file_extension])),
                ('TAN_Document', models.FileField(max_length=200, upload_to='media', validators=[accounts.models.validate_file_extension])),
                ('client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.Client')),
            ],
        ),
    ]
