# Generated by Django 3.0.7 on 2020-07-07 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_clientprofile_partnerprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientprofile',
            name='Official_photo',
            field=models.ImageField(max_length=200, upload_to='media'),
        ),
        migrations.AlterField(
            model_name='clientprofile',
            name='logo',
            field=models.ImageField(max_length=200, upload_to='media'),
        ),
    ]
